source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'ProjectOvaltine' do
    pod 'Alamofire', '~> 3.4'
    pod 'SnapKit', '~> 0.15.0'
    pod 'SwiftyJSON'
    pod 'SwiftSpinner'
    pod 'LFHeatMap'
    pod 'GaugeView'
end